# Generated by Django 5.1.1 on 2024-10-08 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex03', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movies',
            table='ex03_movies',
        ),
    ]
