# Generated by Django 5.1.1 on 2024-10-13 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex10', '0002_movies_characters_alter_people_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='characters',
            field=models.ManyToManyField(related_name='characters', to='ex10.people'),
        ),
    ]
