# Generated by Django 5.1.1 on 2024-10-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex10', '0003_alter_movies_characters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='characters',
            field=models.ManyToManyField(db_constraint=False, null=True, related_name='characters', to='ex10.people'),
        ),
    ]
